// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Url struct {
	UrlID        int32
	OriginalUrl  string
	ShortCode    string
	CustomAlias  sql.NullString
	CreationDate time.Time
	UserID       int32
}

type User struct {
	UserID       int32
	Email        string
	PasswordHash string
	Username     string
	RegisterDate time.Time
}

type Visit struct {
	ClickID   int32
	UrlID     int32
	ClickDate time.Time
	Referrer  sql.NullString
	IpAddress string
	Country   sql.NullString
}
